database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://db:3306/retail_store
  properties:
    useSSL: false
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  maxConnectionAge: 30 minutes

logging:
  level: INFO
  loggers:
    com.omnicuris: INFO

